require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
