AllCops:
  Exclude:
    - 'bin/update'
    - 'bin/setup'
    - 'db/schema.rb'
    - 'node_modules/node-sass/src/libsass/**/*'
Bundler/OrderedGems:
  Enabled: false
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
