services:
  app:
    build: .
    image: app:1.0.0
    volumes:
      - .:/app:cached
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    tmpfs:
      - /tmp
    environment:
      BOOTSNAP_CACHE_DIR: '/app/vendor/bundle'
      BUNDLE_APP_CONFIG: '/app/.bundle'
      BUNDLE_PATH: '/app/vendor/bundle'
      DATABASE_HOST: 'db'
      DATABASE_PASSWORD: 'password'
      DATABASE_USER: 'postgres'
    depends_on:
      - db
    command: /bin/sh -c 'rm -f /app/tmp/pids/server.pid && bundle exec foreman start -f Procfile.dev'
    ports:
      - '3000:3000'
    user: root
    working_dir: /app
  db:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
volumes:
  bundle:
  node_modules:
  rails_cache:
  packs:
  postgres:
